---
version: "3.7"

networks:
  unifi_net:
    name: unifi_net

services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-controller
    networks:
      - unifi_net
    depends_on:
      - mongo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi_user
      - MONGO_PASS=unifi_pass
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - ./unifi/data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped

  mongo:
    image: docker.io/mongo:latest
    container_name: mongodb
    networks:
      - unifi_net
    volumes:
      - ./unifi/mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
